name: firepulse-api-services-override

services:
  config-service:
    image: firepulse-api-config-service
    pull_policy: never

  discovery-service:
    image: firepulse-api-discovery-service
    pull_policy: never

  brigadeflow-service:
    image: firepulse-api-brigadeflow-service
    pull_policy: never

  pyrosense-service:
    image: firepulse-api-pyrosense-service
    pull_policy: never

  stationlogix-service:
    image: firepulse-api-stationlogix-service
    pull_policy: never

networks:
  firepulse_api:
    name: firepulse_api
    driver: bridge
