name: firepulse-api-services

# The `image` and `container_name` fields MUST have the value 'firepulse-api-{service-name}'
services:
  config-service:
    image: ghcr.io/insa-resq/firepulse-api/config-service:${IMAGE_TAG}
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=config-service
    container_name: firepulse-api-config-service
    restart: always
    deploy:
      update_config:
        failure_action: rollback
    ports:
      - '8000:8080'
    networks:
      - firepulse_api
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8080/actuator/health"]
      start_period: 5s
      start_interval: 5s
      interval: 30s
      timeout: 5s
      retries: 3

  discovery-service:
    image: ghcr.io/insa-resq/firepulse-api/discovery-service:${IMAGE_TAG}
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=discovery-service
    container_name: firepulse-api-discovery-service
    restart: always
    deploy:
      update_config:
        failure_action: rollback
    environment:
      - CONFIG_SERVER_URI=http://config-service:8080
    ports:
      - '8001:8080'
    networks:
      - firepulse_api
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8080/actuator/health"]
      start_period: 15s
      start_interval: 5s
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      config-service:
        condition: service_healthy

  detection-service:
    image: ghcr.io/insa-resq/firepulse-api/detection-service:${IMAGE_TAG}
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=detection-service
    container_name: firepulse-api-detection-service
    restart: always
    deploy:
      update_config:
        failure_action: rollback
    environment:
      - CONFIG_SERVER_URI=http://config-service:8080
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '8003:8080'
    networks:
      - firepulse_api
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O-", "http://localhost:8080/actuator/health" ]
      start_period: 45s
      start_interval: 5s
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy

  planning-service:
    image: ghcr.io/insa-resq/firepulse-api/planning-service:${IMAGE_TAG}
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=planning-service
    container_name: firepulse-api-planning-service
    restart: always
    deploy:
      update_config:
        failure_action: rollback
    environment:
      - CONFIG_SERVER_URI=http://config-service:8080
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '8004:8080'
    networks:
      - firepulse_api
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8080/actuator/health"]
      start_period: 45s
      start_interval: 5s
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy

  registry-service:
    image: ghcr.io/insa-resq/firepulse-api/registry-service:${IMAGE_TAG}
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=registry-service
    container_name: firepulse-api-registry-service
    restart: always
    deploy:
      update_config:
        failure_action: rollback
    environment:
      - CONFIG_SERVER_URI=http://config-service:8080
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '8005:8080'
    networks:
      - firepulse_api
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8080/actuator/health"]
      start_period: 45s
      start_interval: 5s
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy

networks:
  firepulse_api:
    name: firepulse_api
    driver: bridge
