name: firepulse-api-services-override

services:
  config-service:
    image: firepulse-api-config-service
    pull_policy: never

  discovery-service:
    image: firepulse-api-discovery-service
    pull_policy: never

  detection-service:
    image: firepulse-api-detection-service
    pull_policy: never

  planning-service:
    image: firepulse-api-planning-service
    pull_policy: never

  registry-service:
    image: firepulse-api-registry-service
    pull_policy: never

networks:
  firepulse_api:
    name: firepulse_api
    driver: bridge
