name: firepulse-api-services

# The `image` and `container_name` fields MUST have the value 'firepulse-api-{service-name}'
services:
  accounts-service:
    image: ghcr.io/insa-resq/firepulse-api/accounts-service:${IMAGE_TAG}
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=accounts-service
    container_name: firepulse-api-accounts-service
    restart: always
    deploy:
      update_config:
        failure_action: rollback
    environment:
      - CONFIG_SERVER_URI=http://config-service:8888
      - EUREKA_SERVER_URI=http://discovery-service:8761/eureka/
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    networks:
      - firepulse_api
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8080/actuator/health/readiness"]
      start_period: 75s
      interval: 10s
      timeout: 7s
      retries: 5
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy

  config-service:
    image: ghcr.io/insa-resq/firepulse-api/config-service:${IMAGE_TAG}
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=config-service
    container_name: firepulse-api-config-service
    restart: always
    deploy:
      update_config:
        failure_action: rollback
    ports:
      - '8888:8888'
    networks:
      - firepulse_api
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8888/actuator/health/readiness"]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  detection-service:
    image: ghcr.io/insa-resq/firepulse-api/detection-service:${IMAGE_TAG}
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=detection-service
    container_name: firepulse-api-detection-service
    restart: always
    deploy:
      update_config:
        failure_action: rollback
    environment:
      - CONFIG_SERVER_URI=http://config-service:8888
      - EUREKA_SERVER_URI=http://discovery-service:8761/eureka/
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    networks:
      - firepulse_api
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O-", "http://localhost:8080/actuator/health/readiness" ]
      start_period: 75s
      interval: 10s
      timeout: 7s
      retries: 5
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy

  discovery-service:
    image: ghcr.io/insa-resq/firepulse-api/discovery-service:${IMAGE_TAG}
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=discovery-service
    container_name: firepulse-api-discovery-service
    restart: always
    deploy:
      update_config:
        failure_action: rollback
    environment:
      - CONFIG_SERVER_URI=http://config-service:8888
    ports:
      - '8761:8761'
    networks:
      - firepulse_api
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8761/actuator/health/readiness"]
      start_period: 45s
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      config-service:
        condition: service_healthy

  gateway-service:
    image: ghcr.io/insa-resq/firepulse-api/gateway-service:${IMAGE_TAG}
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=gateway-service
    container_name: firepulse-api-gateway-service
    restart: always
    deploy:
      update_config:
        failure_action: rollback
    environment:
      - CONFIG_SERVER_URI=http://config-service:8888
      - EUREKA_SERVER_URI=http://discovery-service:8761/eureka/
    ports:
      - '8080:8080'
    networks:
      - firepulse_api
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O-", "http://localhost:8080/actuator/health/readiness" ]
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy

  planning-service:
    image: ghcr.io/insa-resq/firepulse-api/planning-service:${IMAGE_TAG}
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=planning-service
    container_name: firepulse-api-planning-service
    restart: always
    deploy:
      update_config:
        failure_action: rollback
    environment:
      - CONFIG_SERVER_URI=http://config-service:8888
      - EUREKA_SERVER_URI=http://discovery-service:8761/eureka/
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    networks:
      - firepulse_api
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8080/actuator/health/readiness"]
      start_period: 75s
      interval: 10s
      timeout: 7s
      retries: 5
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy

  registry-service:
    image: ghcr.io/insa-resq/firepulse-api/registry-service:${IMAGE_TAG}
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=registry-service
    container_name: firepulse-api-registry-service
    restart: always
    deploy:
      update_config:
        failure_action: rollback
    environment:
      - CONFIG_SERVER_URI=http://config-service:8888
      - EUREKA_SERVER_URI=http://discovery-service:8761/eureka/
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    networks:
      - firepulse_api
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:8080/actuator/health/readiness"]
      start_period: 75s
      interval: 10s
      timeout: 7s
      retries: 5
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy

networks:
  firepulse_api:
    name: firepulse_api
    driver: bridge
